# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integ <- function(dyn, Tmax, N) {
    .Call('_pprmcmc_integ', PACKAGE = 'pprmcmc', dyn, Tmax, N)
}

#' Distance between two locations.
#'
#'\code{distance} returns the square of the distance between two locations.
#'
#' @param phi1,phi2  Longititudes of location 1 and 2 respectively.
#' @param lamda1,lamda2  Latitudes of location 1 and 2 respectively.
#'
#' @return The distance between locations \code{phi1,lamda1} and \code{phi2,lamda2}.
#'
#' @examples
#' distance(10,20,5,10)
#' @export
distance <- function(phi1, phi2, lamda1, lamda2) {
    .Call('_pprmcmc_distance', PACKAGE = 'pprmcmc', phi1, phi2, lamda1, lamda2)
}

#' Sample  a source of infection to the current premisse.
#'
#'\code{Soursamp} returns the index of the source that infect a premisse.
#'
#' @param rtime,time Vector of removals and infections times respectively.
#' @param ind,size,ele Integers indicating the index of the premisse in the vector time,
#'        the size of the potential sources and the premisse selected respectively.
#'
#' @return The index of the source of the premisse at the position \code{ele}.
#' @export
Soursamp <- function(rtime, time, ind, siz, ele) {
    .Call('_pprmcmc_Soursamp', PACKAGE = 'pprmcmc', rtime, time, ind, siz, ele)
}

Which <- function(rhs, key) {
    .Call('_pprmcmc_Which', PACKAGE = 'pprmcmc', rhs, key)
}

#' Check for existence of an element in a vector.
#'
#'\code{contains} returns a boolean either true or false.
#'
#' @param x A vector.
#' @param z An element to be checked.
#'
#' @return True if \code{z} is in vector \code{X} and False otherwise.
#'
#' @examples
#' distance(10,20,5,10)
#' @export
contains <- function(X, z) {
    .Call('_pprmcmc_contains', PACKAGE = 'pprmcmc', X, z)
}

#' Construction of the epidemic process.
#'
#'\code{construct} reconvers the dynamic of the epidemic process. It reorders the events
#'                 as they happened'
#'
#' @param Coo Matrix indicating the locations of all premisses (Longitude,latitude).
#' @param Remtime,Inftime Vectors indicating their corresponding removal and infection
#'        times respectively .
#' @param infper The infectious period.
#' @param NR,Tmax The number of hosts removed and the final observation time.
#' @param M1 2NX5 Matrix to store the dynamic of the process where colomn:
#'       \enumerate{
#'       \item  Contains the events times
#'       \item  Contains the latitude of the infected premisse.
#'       \item  Contains the longititu of the infected premisse.
#'       \item  Indicates the type of event, particulary we o for infection else the
#'              index of host removed.
#'       \item  The trajectory of the epidemic ie the size of the infections.
#'       }
#' @param Indx,size Empty vectors to store the position of premisses in the matrix M1 that
#'        store the process.
#' @param nrows Integer to keep the number of rows used in M1 since there might be more
#'        rows than events.
#'
#' @return The dynamic of the epidemic process, the position of each infection, the size
#'         of the source of infection of each infected premisse and the number of events.
#'
#' @export
construct <- function(Coo, Inftime, infper, NR, Tmax, Indx, size, M1, nrows) {
    invisible(.Call('_pprmcmc_construct', PACKAGE = 'pprmcmc', Coo, Inftime, infper, NR, Tmax, Indx, size, M1, nrows))
}

#' @rdname construct
#' @export
construct1 <- function(Coo, Inftime, Remtime, NR, Tmax, Indx, size, M1, nrows) {
    invisible(.Call('_pprmcmc_construct1', PACKAGE = 'pprmcmc', Coo, Inftime, Remtime, NR, Tmax, Indx, size, M1, nrows))
}

#' Likelihood computation using rayleigh distribution as kernel.
#'
#'\code{likelihood} compute the log-likelihood of the parameters when the kernl is
#' the rayleigh distribution.
#'
#' @param Coo,Inftime Vectors indicating the locations of all premisses and their corresponding
#'        infection times respectively .
#' @param dyn 2NX5 Matrix indicating dynamic of the process where colomn:
#'       \enumerate{
#'       \item  Contains the events times
#'       \item  Contains the latitude of the infected premisse.
#'       \item  Contains the longititu of the infected premisse.
#'       \item  Indicates the type of event, particulary we o for infection else the
#'              index of host removed.
#'       \item  The trajectory of the epidemic ie the size of the infections.
#'       }
#' @param Sou_siz,S Vectors indicating the potential source size, the position of premisses
#'        in the matrix M1 that store the process.
#' @param beta,alpha The contact and the dispersal parameters.
#' @param nrows Integer indicating the number of rows used in dyn since there might be more
#'        rows than events.
#' @return The log-likelihood of the parameters.
#' @export
likelihood <- function(Coo, Sou_siz, S, dyn, beta, alpha, nrows) {
    .Call('_pprmcmc_likelihood', PACKAGE = 'pprmcmc', Coo, Sou_siz, S, dyn, beta, alpha, nrows)
}

lik <- function(alpha, S, mat) {
    .Call('_pprmcmc_lik', PACKAGE = 'pprmcmc', alpha, S, mat)
}

#' Parameter estimation with MCMC.
#'
#' Sample from the posterior distribution of the contact rate, the kernel parameter and
#' the infectious period using rayleigh (\code{raymcmc}), exponential (\code{expmcmc}) and cauchy (\code{caumcmc}) kernels.
#'
#' This is a Markov Chain Monte Carlo (MCMC) technique to sample from the posterior distribution
#' of the model parameters. It uses Gibbs sampling \url{https://en.wikipedia.org/wiki/Gibbs_sampling}
#' to sample from the model parametes and use data augmentation technique to change in the
#' transmission network.
#'
#' @param Coo A NX2 matrix indicating the location (longitude latitude) of infected hosts with N the size of the
#'        infected population.
#' @param Sourc,Inftim  Vector of length N indicating the initial source of infection of every host
#'        with -1 for the first infection and the corresponding infection times respectively.
#' @param nits,lmin,lmax,Tmax Indicate the number of iterations (10000 by default), the lower and upper bound of the prior
#'        infectious period (0 and 110 by defaut) and the final observation time (325 by default)  respectively.
#' @param a,b,c,d The gamma conjugate priors for the parametes. Vague priors are considere as default.
#' @param theta   A vector of size 3 indicating the initial values for the parameters alpha, beta and gamma.
#' @return A nitsX3 matrix indicating sample from the posterior distributions of alpha, beta and gamma.
#'
#' @import ggplot2
#'
#' @examples
#' data(ppr)
#' attach(ppr)
#' #Premisses locations
#' Coo=matrix(c(ppr$Longitude,ppr$Latitude),nrow=26,ncol=2,byrow=F)
#'
#' #Infection times
#' diff=as.Date(Date.of.start.of.the.outbreak)-as.Date(Date.of.start.of.the.outbreak)[1]
#' inf=as.numeric(diff)
#' inf[2:26]=inf[2:26]+runif(25)
#' Inftim=sort(inf)
#'
#' #Initial sources
#' infper=110
#' rt=Inftim + infper
#' Sourc=numeric(26)
#' for(i in 2:26){
#' a=which(Inftim[i]>Inftim)
#' b=which(Inftim[i]<rt)
#' l=a[a%in%b]
#' Sourc[i]=sample(l,1)
#' }
#' Sourc=Sourc-1
#'
#'#Rayleigh kernel
#' a=raymcmc(Coo, Sourc,Inftim)
#' a=raymcmc(Coo, Sourc,Inftim,nits=100000)
#' #a=caumcmc(Coo, Sourc,Inftim,nits=10000,theta=c(.1,.3,infper))
#' b=data.frame(a[10000:100000,])
#' colnames(b)=c("V1","V2","V3")
#' require("ggplot2")
#' qplot(1/sqrt(2*V1),data=b,geom='histogram',xlab=bquote(alpha~(km)),ylab='',xlim=c(50,150))+ geom_histogram(aes(fill = ..count..)) +theme(legend.position="none")
#' qplot(V2,data=b,geom='histogram',xlab=bquote(beta~(days^-1~km)),ylab='',xlim=c(0,.02))+ geom_histogram(aes(fill = ..count..)) +theme(legend.position="none")
#' qplot(V3,data=b,geom='histogram',xlab=bquote('Infectious period'~(days^-1)),ylab='')+ geom_histogram(aes(fill = ..count..)) +theme(legend.position="none")
#'
#'#Exponential kernel
#' a=expmcmc(Coo, Sourc,Inftim,nits=100000,theta=c(.1,.3,infper))
#' colnames(b)=c("V1","V2","V3")
#' qplot(1/V1,data=b,geom='histogram',xlab=bquote(alpha~(km)),ylab='',xlim=c(25,250))+ geom_histogram(aes(fill = ..count..)) +theme(legend.position="none")
#' qplot(V2,data=b,geom='histogram',xlab=bquote(beta~(days^-1~km)),ylab='',xlim=c(0,.02))+ geom_histogram(aes(fill = ..count..)) +theme(legend.position="none")
#' qplot(V3,data=b,geom='histogram',xlab=bquote('Infectious period'~(days^-1)),ylab='')+ geom_histogram(aes(fill = ..count..)) +theme(legend.position="none")
#'
#'#Cauchy kernel
#' a=caumcmc(Coo, Sourc,Inftim,nits=100000,theta=c(.1,.3,infper))
#' b=data.frame(a[10000:100000,])
#' colnames(b)=c("V1","V2","V3")
#' qplot(V1,data=b,geom='histogram',xlab=bquote(alpha~(km)),ylab='',xlim=c(40,350))+ geom_histogram(aes(fill = ..count..)) +theme(legend.position="none")
#' qplot(V2,data=b,geom='histogram',xlab=bquote(beta~(days^-1~km)),ylab='',xlim=c(0.0025,.02))+ geom_histogram(aes(fill = ..count..)) +theme(legend.position="none")
#' qplot(V3,data=b,geom='histogram',xlab=bquote('Infectious period'~(days^-1)),ylab='')+ geom_histogram(aes(fill = ..count..)) +theme(legend.position="none")
#' @export
raymcmc <- function(Coo, Sourc, Inftim, nits = 1000L, lmin = 0L, lmax = 120L, Tmax = 325L, a = 1e-4, b = 10e-6, c = 1e-3, d = 1e-4, theta = as.numeric( c(1.0,2.0,110))) {
    .Call('_pprmcmc_raymcmc', PACKAGE = 'pprmcmc', Coo, Sourc, Inftim, nits, lmin, lmax, Tmax, a, b, c, d, theta)
}

#' @rdname raymcmc
#' @export
expmcmc <- function(Coo, Sourc, Inftim, nits = 1000L, lmin = 0L, lmax = 120L, Tmax = 325L, a = 1e-4, b = 10e-6, c = 1e-3, d = 1e-4, theta = as.numeric( c(1.0,2.0,110))) {
    .Call('_pprmcmc_expmcmc', PACKAGE = 'pprmcmc', Coo, Sourc, Inftim, nits, lmin, lmax, Tmax, a, b, c, d, theta)
}

#' @rdname raymcmc
#' @export
caumcmc <- function(Coo, Sourc, Inftim, nits = 1000L, lmin = 0L, lmax = 120L, Tmax = 325L, a = 1e-4, b = 10e-6, c = 1e-3, d = 1e-4, theta = as.numeric( c(1.0,2.0,110))) {
    .Call('_pprmcmc_caumcmc', PACKAGE = 'pprmcmc', Coo, Sourc, Inftim, nits, lmin, lmax, Tmax, a, b, c, d, theta)
}

